### PR TITLE
Finish off work for Beautify Touchpad (#3) issue.

### PR DESCRIPTION
**Pull request by dbarrous**
**PR continues work by @jjcrab:** https://github.com/shubham1172/remote-play/pull/8

## What this PR does:
- Adds `style.scss` file used by Sass compiler, which also adds the proper CSS prefixes to improve browser compatibility.
- Removes comments from `index.html` file.
- Removes Bulma class names from `index.html` file.
- Recreates Hero Bulma class using vanilla CSS.
- Recreates Footer using vanilla CSS.
- Fixes issue with buttons staying highlighted on mobile.
- Added some margin between header + buttons + footer.

## Screenshot:
screenshot_webapp

### CODE REVIEW

**Comment by shubham1172** [comment]
@dbarrous can you please rebase this with main? Looks like this is a lot of commits behind.

**Comment by shubham1172** [comment]
Thanks for the PR, the high-level code changes LGTM and so does the new UI! 👍🏻

**Comment by dbarrous** [comment]
@shubham1172 Rebased :)

**Review by shubham1172 — CHANGES_REQUESTED** [review]
Thank you, this is awesome!
1. Can we add the current screenshot and replace `docs\screenshot_webapp.jpeg`?
2. How do we convert scss to css? It will be useful to put some instructions on the same in `CONTRIBUTING.md`

**Comment by dbarrous** [comment]
@shubham1172 Screenshot updated & Contributing doc updated with instructions on how to convert `.scss` files to `.css`.

**Review by shubham1172 — APPROVED** [review]
Thank you so much @dbarrous for fixing this! 🎉

**Pull request merged**
